version: '3'
services:

  #PHP Service
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: davidguardia.com/php
    container_name: web
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laranet

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laranet
    
  #MySQL Service
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravelroot
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laranet
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - laranet

#Docker Networks
networks:
  laranet:
    driver: "bridge"
#Volumes
volumes:
  dbdata:
    driver: "local"
  redisdata:
    driver: "local"